### ISSUE TITLE
Problem Java version

### ISSUE THREAD

**Issue by lhoreman** [fesch/Structorizer.Desktop#152]
Several people are having problems installing structorizer on the latest OS-versions for Windows and Mac. Some get the message that they need to downgrade their Java-version. Could you look into this please?

**Comment by fesch** [comment]
Of course, but I need more detailed information about the used OS and the error message (maybe from the command line ....)

**Comment by codemanyak** [comment]
@lhoreman I would like to add: With respect to Windows it's interesting to know if you use Java WebStart or the zipped download (with the latter I can't detect a problem with the most up-to-date Java release - it's rather the other way round -, so perhaps the WebStart code is outdated?)

**Comment by lhoreman** [comment]
One person works with OS X El Capitan, versie 10.11.4.  She tried to install the full version (3.23). She has to install Java SE6.
We noticed some people have problems on Windows 7 and Windows 10 but we don't have the specifics.

**Comment by codemanyak** [comment]
@lhoreman Ah, there's the rub! She should definitely try 3.24 or the latest development version (3.24-05). Version 3.23 came with a misleading Java version specification.

**Comment by codemanyak** [comment]
Moreover, release 3.23 is - from a functional aspect - stone age already ;-)

**Comment by lhoreman** [comment]
I will ask her. I let you know!

**Comment by codemanyak** [comment]
@lhoreman I just see, she actually needs the most recent version. The java target specification was only corrected after release 3.24.

**Comment by codemanyak** [comment]
@fesch Against my assumptions, the info.plist file still specifies JavaVMVersion "1.6+". Is this due to the wrapper problems you reported on occasion of pull request #136?

**Comment by fesch** [comment]
That is correct, so a JVM of at least 1.6 will be needed, otherwise the OSX wrapper will not start. This means, that any JVM 1.8 oder 1.7 will work too. I'm working on a Mac with only Java 8 installed and it works fine.

**Comment by fesch** [comment]
Just tested this on a blank El Capitan installation and I can now confirm that the OS really asks to install Java 6 :-(

**Comment by codemanyak** [comment]
So it seems to be the identical problem already reported in issue #79 and perhaps the same remedy will have to be recommended (though lowering the security level is hardly a good recommendation in general)...

**Comment by fesch** [comment]
Okay, I've deployed now something called "AppBundler" from Oracle. I've used this for Unimozer as well. After compiling (this time with Java 8 code!) and packaging, the new package works on my El Capitan Mac.

@lhoreman : please try redownload the Mac package an try again. It may be possible that you need to restart your Mac to empty the Java cache.

**Comment by lhoreman** [comment]
@Fesch: The problem isn't solved. Structorizer still asks a old version of Java

**Comment by fesch** [comment]
Did you restart and make sure the Java cache has been emptied? I had the same this afternoon when testing. At the beginning it did not work, but later on, after the reboot, the same binary started working.

**Comment by fesch** [comment]
What about the Windows problems? Did the new package solve these?

**Comment by codemanyak** [comment]
@lhoreman 
Please confirm either that the problem is still existent or that it is solved. Otherwise we will close the issue by the end of the month.

**Comment by codemanyak** [comment]
Closed due to missing response of the originator.
